// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToDoListApp.Service.WebAPI.Data.Context.EfCore;

namespace ToDoListApp.Service.WebAPI.Migrations
{
    [DbContext(typeof(ToDoListContext))]
    [Migration("20210504220544_initialCreate")]
    partial class initialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ToDoListApp.Service.WebAPI.Entities.MyTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDone")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRemind")
                        .HasColumnType("boolean");

                    b.Property<string>("TaskContent")
                        .HasColumnType("text");

                    b.Property<DateTime>("TaskDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TaskTitle")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Tasks", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 5, 5, 1, 5, 43, 656, DateTimeKind.Local).AddTicks(4206),
                            IsDelete = false,
                            IsDone = true,
                            IsRemind = false,
                            TaskContent = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
                            TaskDate = new DateTime(2021, 5, 5, 1, 5, 43, 659, DateTimeKind.Local).AddTicks(612),
                            TaskTitle = "Lorem Ipsum",
                            UpdatedAt = new DateTime(2021, 5, 5, 1, 5, 43, 658, DateTimeKind.Local).AddTicks(6023)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2021, 5, 5, 1, 5, 43, 659, DateTimeKind.Local).AddTicks(1678),
                            IsDelete = false,
                            IsDone = false,
                            IsRemind = false,
                            TaskContent = "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
                            TaskDate = new DateTime(2021, 5, 5, 1, 5, 43, 659, DateTimeKind.Local).AddTicks(1796),
                            TaskTitle = "Contrary to popular",
                            UpdatedAt = new DateTime(2021, 5, 5, 1, 5, 43, 659, DateTimeKind.Local).AddTicks(1707)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2020, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDelete = false,
                            IsDone = true,
                            IsRemind = false,
                            TaskContent = "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.",
                            TaskDate = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TaskTitle = "Contrary to popula",
                            UpdatedAt = new DateTime(2020, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2020, 5, 5, 1, 5, 43, 659, DateTimeKind.Local).AddTicks(1881),
                            IsDelete = true,
                            IsDone = true,
                            IsRemind = false,
                            TaskContent = "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.",
                            TaskDate = new DateTime(2021, 5, 5, 1, 5, 43, 659, DateTimeKind.Local).AddTicks(2043),
                            TaskTitle = "There are many variations",
                            UpdatedAt = new DateTime(2020, 6, 5, 1, 5, 43, 659, DateTimeKind.Local).AddTicks(2024)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2018, 5, 5, 1, 5, 43, 659, DateTimeKind.Local).AddTicks(2049),
                            IsDelete = false,
                            IsDone = false,
                            IsRemind = false,
                            TaskContent = "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.",
                            TaskDate = new DateTime(2021, 5, 5, 1, 5, 43, 659, DateTimeKind.Local).AddTicks(2210),
                            TaskTitle = "There are many variations",
                            UpdatedAt = new DateTime(2019, 7, 20, 1, 5, 43, 659, DateTimeKind.Local).AddTicks(2055)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
